name: "Austin Eng - Projects, Code, and Blog"
description: "Austin Eng is a Computer Graphics student at the University of Pennsylvania with many interest ranging from Computer Science to Robotics and Computer Vision. He has interned at Walt Disney Animation Studios as well as multiple software companies."

baseurl: ""

permalink: /:categories/:title

defaults:
  -
    scope:
      path: ""
      type: post
    values:
      layout: project
      is_blog: ["false"]
  -
    scope:
      path: "blog"
      type: post
    values:
      layout: blog
      is_blog: ["true"]
      author: Austin Eng

markdown: redcarpet
highlighter: pygments

sass:
  style: :compressed

gems:
  - jekyll-sitemap