name: Austin Eng
description: "Austin Eng - Projects, Code, and Blog of a Computer Graphics student at the University of Pennsylvania"

baseurl: ""

permalink: /:categories/:title

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: project
      is_blog: ["false"]
  -
    scope:
      path: "blog"
      type: posts
    values:
      layout: blogpost
      is_blog: ["true"]
      author: Austin Eng

markdown: redcarpet
highlighter: pygments

sass:
  style: :compressed

gems:
  - jekyll-sitemap